"""refatora as tags

Revision ID: 092b86e1e59c
Revises: 42a47f86e559
Create Date: 2025-12-18 15:30:21.765394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '092b86e1e59c'
down_revision: Union[str, Sequence[str], None] = '42a47f86e559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id_tag', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id_tag'),
    sa.UniqueConstraint('user_email', 'name')
    )
    op.create_table('task_tag',
    sa.Column('id_task', sa.Integer(), nullable=False),
    sa.Column('id_tag', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tag'], ['tags.id_tag'], ),
    sa.ForeignKeyConstraint(['id_task'], ['tasks.id_task'], ),
    sa.PrimaryKeyConstraint('id_task', 'id_tag')
    )
    op.drop_column('tasks', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('tags', sqlite.JSON(), nullable=True))
    op.drop_table('task_tag')
    op.drop_table('tags')
    # ### end Alembic commands ###
