"""create task_occurrences table

Revision ID: 651fe08e550e
Revises: 0e7212850d2e
Create Date: 2026-10-05 19:16:50.504890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '651fe08e550e'
down_revision: Union[str, Sequence[str], None] = '0e7212850d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_occurrences',
    sa.Column('id_task_occurrence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_task', sa.Integer(), nullable=False),
    sa.Column('occurrence_date', sa.DateTime(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_task'], ['tasks.id_task'], ),
    sa.PrimaryKeyConstraint('id_task_occurrence'),
    sa.UniqueConstraint('id_task', 'occurrence_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_occurrences')
    # ### end Alembic commands ###
