"""create table tasks

Revision ID: e0a9edb5c06c
Revises: d85fc651fb3d
Create Date: 2025-10-13 18:53:41.482348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0a9edb5c06c'
down_revision: Union[str, Sequence[str], None] = 'd85fc651fb3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id_task', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_user', sa.String(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('reminder', sa.DateTime(), nullable=False),
    sa.Column('repetition', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['email_user'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id_task')
    )
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_table('tasks')
    # ### end Alembic commands ###
