"""update_table_tags

Revision ID: 0e7212850d2e
Revises: c6db2efc86f5
Create Date: 2026-03-04 17:50:22.839601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e7212850d2e'
down_revision: Union[str, Sequence[str], None] = 'c6db2efc86f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('color_hex', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'color_hex')
    # ### end Alembic commands ###
