"""create views and filters table

Revision ID: c6db2efc86f5
Revises: 042d4cc93972
Create Date: 2026-02-16 13:07:30.931329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6db2efc86f5'
down_revision: Union[str, Sequence[str], None] = '042d4cc93972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('views',
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id_view', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id_view'),
    sa.UniqueConstraint('user_email', 'name')
    )
    op.create_table('filters',
    sa.Column('id_view', sa.Integer(), nullable=False),
    sa.Column('id_filter', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('reminder', sa.JSON(), nullable=True),
    sa.Column('repetition', sa.String(), nullable=True),
    sa.Column('state', sa.JSON(), nullable=True),
    sa.Column('priority', sa.JSON(), nullable=True),
    sa.Column('offset', sa.Integer(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id_view'], ['views.id_view'], ),
    sa.PrimaryKeyConstraint('id_filter')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filters')
    op.drop_table('views')
    # ### end Alembic commands ###
